config/routes.rb
Mylab::Application.routes.draw do
  resources :equipment

  

end

app/models/equipment.rb
class Equipment < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/equipment_controller.rb
class EquipmentController < ApplicationController
  before_action :set_equipment, only: [:show, :edit, :update, :destroy]

  # GET /equipment
  # GET /equipment.json
  def index
    @equipment = Equipment.all
  end

  # GET /equipment/1
  # GET /equipment/1.json
  def show
  end

  # GET /equipment/new
  def new
    @equipment = Equipment.new
  end

  # GET /equipment/1/edit
  def edit
  end

  # POST /equipment
  # POST /equipment.json
  def create
    @equipment = Equipment.new(equipment_params)

    respond_to do |format|
      if @equipment.save
        format.html { redirect_to @equipment, notice: 'Equipment was successfully created.' }
        format.json { render action: 'show', status: :created, location: @equipment }
      else
        format.html { render action: 'new' }
        format.json { render json: @equipment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /equipment/1
  # PATCH/PUT /equipment/1.json
  def update
    respond_to do |format|
      if @equipment.update(equipment_params)
        format.html { redirect_to @equipment, notice: 'Equipment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @equipment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /equipment/1
  # DELETE /equipment/1.json
  def destroy
    @equipment.destroy
    respond_to do |format|
      format.html { redirect_to equipment_index_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_equipment
      @equipment = Equipment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def equipment_params
      params[:equipment]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/equipment_helper.rb
module EquipmentHelper
end

app/views/equipment/_form.html.erb
<%= form_for(@equipment) do |f| %>
  <% if @equipment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@equipment.errors.count, "error") %> prohibited this equipment from being saved:</h2>

      <ul>
      <% @equipment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/equipment/edit.html.erb
<h1>Editing equipment</h1>

<%= render 'form' %>

<%= link_to 'Show', @equipment %> |
<%= link_to 'Back', equipment_index_path %>

app/views/equipment/index.html.erb
<h1>Listing equipment</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @equipment.each do |equipment| %>
      <tr>
        <td><%= link_to 'Show', equipment %></td>
        <td><%= link_to 'Edit', edit_equipment_path(equipment) %></td>
        <td><%= link_to 'Destroy', equipment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Equipment', new_equipment_path %>

app/views/equipment/new.html.erb
<h1>New equipment</h1>

<%= render 'form' %>

<%= link_to 'Back', equipment_index_path %>

app/views/equipment/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_equipment_path(@equipment) %> |
<%= link_to 'Back', equipment_index_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mylab</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>